package br.com.iagocolodetti.chatsocket;

import java.awt.Cursor;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author iagocolodetti
 */
public class ServidorForm extends javax.swing.JFrame {

    private final int MIN_PORTA = 0;
    private final int MAX_PORTA = 65535;

    private Servidor servidor;
    private List<Cliente> clientes;
    
    private final DefaultTableModel jtParticipantesModel;

    /**
     * Creates new form ServidorForm
     */
    public ServidorForm() {
        initComponents();

        jtfIP.setEditable(false);
        jtfIP.setCursor(new Cursor(Cursor.TEXT_CURSOR));

        jtfPorta.requestFocus();

        jtaChat.setEditable(false);
        jtaChat.setCursor(new Cursor(Cursor.TEXT_CURSOR));

        DefaultCaret caret = (DefaultCaret) jtaChat.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        
        jtParticipantesModel = (DefaultTableModel) jtParticipantes.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfIP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfPorta = new javax.swing.JTextField();
        jbLigar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaChat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaMensagem = new javax.swing.JTextArea();
        jbEnviar = new javax.swing.JButton();
        jbLimparChat = new javax.swing.JButton();
        jbLimparMensagem = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtParticipantes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ChatSocket (Servidor)");
        setName("ServidorForm"); // NOI18N
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("IP:");

        jtfIP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfIP.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Porta:");

        jtfPorta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfPorta.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jbLigar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbLigar.setText("LIGAR");
        jbLigar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLigarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chat", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jtaChat.setColumns(20);
        jtaChat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtaChat.setLineWrap(true);
        jtaChat.setRows(5);
        jtaChat.setWrapStyleWord(true);
        jtaChat.setFocusable(false);
        jScrollPane1.setViewportView(jtaChat);

        jtaMensagem.setColumns(20);
        jtaMensagem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtaMensagem.setLineWrap(true);
        jtaMensagem.setRows(3);
        jtaMensagem.setWrapStyleWord(true);
        jtaMensagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtaMensagemKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtaMensagemKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jtaMensagem);

        jbEnviar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbEnviar.setText("Enviar");
        jbEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbEnviar.setEnabled(false);
        jbEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEnviarActionPerformed(evt);
            }
        });

        jbLimparChat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbLimparChat.setText("Limpar Chat");
        jbLimparChat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbLimparChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparChatActionPerformed(evt);
            }
        });

        jbLimparMensagem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbLimparMensagem.setText("Limpar Mensagem");
        jbLimparMensagem.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbLimparMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparMensagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbLimparChat, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbLimparMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbEnviar)
                    .addComponent(jbLimparChat)
                    .addComponent(jbLimparMensagem))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Participantes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jtParticipantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IP", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtParticipantes.setRowSelectionAllowed(false);
        jScrollPane3.setViewportView(jtParticipantes);
        if (jtParticipantes.getColumnModel().getColumnCount() > 0) {
            jtParticipantes.getColumnModel().getColumn(0).setMinWidth(30);
            jtParticipantes.getColumnModel().getColumn(0).setPreferredWidth(50);
            jtParticipantes.getColumnModel().getColumn(1).setMinWidth(50);
            jtParticipantes.getColumnModel().getColumn(1).setPreferredWidth(80);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfIP, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jbLigar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jtfPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLigar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbLigarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLigarActionPerformed
        if (jbLigar.getText().equals("LIGAR")) {
            String sPorta = jtfPorta.getText().trim();
            if (!sPorta.isEmpty()) {
                try {
                    int porta = Integer.parseInt(sPorta);
                    if (porta >= MIN_PORTA && porta <= MAX_PORTA) {
                        setServidorLigado(porta);
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "O número da porta deve ser um inteiro positivo de no mínimo " + MIN_PORTA + " e no máximo " + MAX_PORTA + ".", "Erro", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(rootPane, "A porta deve ser um número inteiro positivo de no mínimo " + MIN_PORTA + " e no máximo " + MAX_PORTA + ".", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Digite a porta em que deseja ligar o serviço.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            setServidorLigado(-1);
        }
    }//GEN-LAST:event_jbLigarActionPerformed

    private void jbEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEnviarActionPerformed
        enviarMensagem();
    }//GEN-LAST:event_jbEnviarActionPerformed

    private void jbLimparChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparChatActionPerformed
        jtaChat.setText("");
    }//GEN-LAST:event_jbLimparChatActionPerformed

    private void jbLimparMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparMensagemActionPerformed
        jtaMensagem.setText("");
    }//GEN-LAST:event_jbLimparMensagemActionPerformed

    private void jtaMensagemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaMensagemKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            enviarMensagem();
        }
    }//GEN-LAST:event_jtaMensagemKeyPressed

    private void jtaMensagemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaMensagemKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && jbLigar.getText().equals("DESLIGAR") && servidor != null) {
            jtaMensagem.setText(jtaMensagem.getText().trim());
        }
    }//GEN-LAST:event_jtaMensagemKeyReleased

    private void addMensagem(String text) {
        if (jtaChat.getText().toString().isEmpty()) {
            jtaChat.append(text);
        } else {
            jtaChat.append("\n" + text);
        }
    }
    
    private void addParticipante(String ip, String nome) {
        jtParticipantesModel.addRow(new Object[]{ ip, nome });
    }
    
    private void removerParticipante(String ip, String nome) {
        for (int i = 0; i < jtParticipantesModel.getRowCount(); i++) {
            if (jtParticipantesModel.getValueAt(i, 0).equals(ip) && jtParticipantesModel.getValueAt(i, 1).equals(nome)) {
                jtParticipantesModel.removeRow(i);
                break;
            }
        }
    }
    
    private String getParticipantes() {
        String participantes = "";
        for (int i = 0; i < jtParticipantesModel.getRowCount(); i++) {
            participantes += jtParticipantesModel.getValueAt(i, 1) + " ";
        }
        return participantes;
    }

    private void setServidorLigado(int porta) {
        if (porta != -1) {
            jtfPorta.setEditable(false);
            jtfPorta.setCursor(new Cursor(Cursor.TEXT_CURSOR));
            jbLigar.setText("DESLIGAR");
            jbEnviar.setEnabled(true);
            clientes = new ArrayList<>();
            servidor = new Servidor(porta);
            Thread thread = new Thread(servidor);
            thread.start();
        } else {
            for (Cliente cliente : clientes) {
                cliente.fechar();
            }
            if (servidor != null) {
                servidor.fechar();
            }
            servidor = null;
            jtParticipantesModel.setRowCount(0);
            jtfPorta.setEditable(true);
            jtfIP.setText("");
            jbLigar.setText("LIGAR");
            jbEnviar.setEnabled(false);
        }
    }
    
    private void enviarMensagem() {
        if (jbLigar.getText().equals("DESLIGAR") && servidor != null) {
            String mensagem = jtaMensagem.getText();
            if (!mensagem.trim().isEmpty()) {
                try {
                    jtaMensagem.setText("");
                    jtaMensagem.requestFocus();
                    servidor.enviar(mensagem.trim());
                } catch (IOException e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(rootPane, "Não foi possível enviar a mensagem.", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                jtaMensagem.setText("");
                JOptionPane.showMessageDialog(rootPane, "O campo destinado a mensagem está vazio.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private class Servidor implements Runnable {
        
        private ServerSocket serverSocket;
        private Socket socket;
        
        private volatile boolean ligado;

        private final int porta;

        public Servidor(int porta) {
            ligado = true;
            this.porta = porta;
        }

        public void fechar() {
            ligado = false;
            try {
                if (socket != null) {
                    socket.close();
                }
                if (serverSocket != null) {
                    serverSocket.close();
                }
            } catch (IOException e) {
                e.printStackTrace();
            } finally {
                socket = null;
                serverSocket = null;
            }
        }
        
        public void enviar(String mensagem) throws IOException {
            if (ligado) {
                try {
                    for (Cliente cliente : clientes) {
                        cliente.enviar("m", "Servidor: " + mensagem.trim());
                    }
                    addMensagem("Você: " + mensagem.trim());
                } catch (IOException e) {
                    throw e;
                }
            }
        }

        @Override
        public void run() {
            try {
                try {
                    serverSocket = new ServerSocket(porta);
                } catch (IOException e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(rootPane, "Não foi possível ligar o serviço, verifique se a porta já está em uso ou se a rede está funcionando.", "Erro", JOptionPane.ERROR_MESSAGE);
                    setServidorLigado(-1);
                    return;
                }

                jtfIP.setText(InetAddress.getLocalHost().getHostAddress());
                addMensagem("Chat ligado.");

                while (ligado) {
                    socket = serverSocket.accept();
                    Cliente cliente = new Cliente(socket);
                    clientes.add(cliente);
                    Thread thread = new Thread(cliente);
                    thread.start();
                }
            } catch (HeadlessException | IOException e) {
                addMensagem("Chat desligado.");
                setServidorLigado(-1);
            }
        }
    }
    
    private class Cliente implements Runnable {
        
        private Socket socket;
        
        private final String ip;
        private String nome;

        private volatile boolean conectado;
        
        public Cliente(Socket socket) {
            conectado = true;
            ip = (((InetSocketAddress) socket.getRemoteSocketAddress()).getAddress()).toString().replace("/", "");
            this.socket = socket;
        }
        
        public String getNome() {
            return nome;
        }
        
        public void fechar() {
            conectado = false;
            try {
                if (socket != null) {
                    socket.close();
                }
            } catch (IOException e) {
                e.printStackTrace();
            } finally {
                socket = null;
            }
        }
        
        public void enviar(String tipo, String mensagem) throws IOException {
            if (conectado) {
                try {
                    DataOutputStream dos = new DataOutputStream(socket.getOutputStream());
                    dos.writeUTF(tipo + mensagem);
                } catch (IOException e) {
                    throw e;
                }
            }
        }

        @Override
        public void run() {
            try {
                DataInputStream dis = new DataInputStream(socket.getInputStream());
                nome = dis.readUTF();
                if (nome.isEmpty()) {
                    enviar("m", "Você precisa fornecer um nome.");
                    clientes.remove(this);
                    fechar();
                    return;
                }
                if (nome.length() < 3 || nome.length() > 20 || nome.contains(" ")) {
                    enviar("m", "O nome deve ter de 3 à 20 caracteres e não pode ter espaços.");
                    clientes.remove(this);
                    fechar();
                    return;
                }
                if (nome.toLowerCase().equals("servidor")) {
                    enviar("m", "O nome 'Servidor' é reservado.");
                    clientes.remove(this);
                    fechar();
                    return;
                }
                for (Cliente cliente : clientes) {
                    if (!this.equals(cliente) && nome.toLowerCase().equals(cliente.getNome().toLowerCase())) {
                        enviar("m", "O nome '" + nome + "' já está em uso.");
                        clientes.remove(this);
                        fechar();
                        return;
                    }
                }
                addMensagem(nome + " entrou no chat. (" + ip + ")");
                addParticipante(ip, nome);
                enviar("p", getParticipantes());
                for (Cliente cliente : clientes) {
                    if (!this.equals(cliente)) {
                        cliente.enviar("e", nome + " entrou no chat.");
                    }
                }
            } catch (Exception e) {
                clientes.remove(this);
                fechar();
            }
            
            while (conectado) {
                try {
                    DataInputStream dis = new DataInputStream(socket.getInputStream());
                    String mensagem = dis.readUTF();
                    addMensagem(nome + ": " + mensagem);
                    for (Cliente cliente : clientes) {
                        if (!this.equals(cliente)) {
                            cliente.enviar("m", nome + ": " + mensagem);
                        }
                    }
                } catch (IOException e) {
                    if (conectado) {
                        addMensagem(nome + " saiu do chat. (" + ip + ")");
                        clientes.remove(this);
                        removerParticipante(ip, nome);
                        try {
                            for (Cliente cliente : clientes) {
                                cliente.enviar("s", nome + " saiu do chat.");
                            }
                        } catch (IOException ex) {
                            ex.printStackTrace();
                        } finally {
                            fechar();
                        }
                    }
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServidorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServidorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServidorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServidorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
                    e.printStackTrace();
                }
                ServidorForm serverForm = new ServidorForm();
                serverForm.setSize(800, 540);
                serverForm.setLocation(
                        (Toolkit.getDefaultToolkit().getScreenSize().width - serverForm.getWidth()) / 2,
                        (Toolkit.getDefaultToolkit().getScreenSize().height - serverForm.getHeight()) / 2);
                serverForm.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbEnviar;
    private javax.swing.JButton jbLigar;
    private javax.swing.JButton jbLimparChat;
    private javax.swing.JButton jbLimparMensagem;
    private javax.swing.JTable jtParticipantes;
    private javax.swing.JTextArea jtaChat;
    private javax.swing.JTextArea jtaMensagem;
    private javax.swing.JTextField jtfIP;
    private javax.swing.JTextField jtfPorta;
    // End of variables declaration//GEN-END:variables
}
